// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using MiniLearningPlatform.Api.Data;

#nullable disable

namespace MiniLearningPlatform.Api.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("MiniLearningPlatform.Api.Models.Course", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Courses");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "Learn the fundamentals of C# programming.",
                            Title = "Introduction to C#"
                        },
                        new
                        {
                            Id = 2,
                            Description = "Build web APIs using ASP.NET Core.",
                            Title = "ASP.NET Core Basics"
                        },
                        new
                        {
                            Id = 3,
                            Description = "Learn relational database design and T-SQL.",
                            Title = "SQL Server Essentials"
                        },
                        new
                        {
                            Id = 4,
                            Description = "Build interactive UIs with vanilla JavaScript.",
                            Title = "Frontend with JavaScript"
                        });
                });

            modelBuilder.Entity("MiniLearningPlatform.Api.Models.Enrollment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CourseId")
                        .HasColumnType("int");

                    b.Property<DateTime>("EnrolledAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CourseId");

                    b.HasIndex("UserId", "CourseId")
                        .IsUnique();

                    b.ToTable("Enrollments");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CourseId = 1,
                            EnrolledAtUtc = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            UserId = 1
                        });
                });

            modelBuilder.Entity("MiniLearningPlatform.Api.Models.Lesson", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("CourseId")
                        .HasColumnType("int");

                    b.Property<int>("Order")
                        .HasColumnType("int");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("CourseId");

                    b.ToTable("Lessons");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Content = "Introduction to C# variables and data types.",
                            CourseId = 1,
                            Order = 1,
                            Title = "Variables & Types"
                        },
                        new
                        {
                            Id = 2,
                            Content = "If statements, loops, and switch expressions.",
                            CourseId = 1,
                            Order = 2,
                            Title = "Control Flow"
                        },
                        new
                        {
                            Id = 3,
                            Content = "Object-oriented basics in C#.",
                            CourseId = 1,
                            Order = 3,
                            Title = "Classes & Objects"
                        },
                        new
                        {
                            Id = 4,
                            Content = "Building endpoints with Minimal APIs.",
                            CourseId = 2,
                            Order = 1,
                            Title = "Minimal APIs"
                        },
                        new
                        {
                            Id = 5,
                            Content = "Using the built-in DI container.",
                            CourseId = 2,
                            Order = 2,
                            Title = "Dependency Injection"
                        },
                        new
                        {
                            Id = 6,
                            Content = "Understanding the request pipeline.",
                            CourseId = 2,
                            Order = 3,
                            Title = "Middleware"
                        },
                        new
                        {
                            Id = 7,
                            Content = "Designing tables, primary and foreign keys.",
                            CourseId = 3,
                            Order = 1,
                            Title = "Tables & Keys"
                        },
                        new
                        {
                            Id = 8,
                            Content = "INNER, LEFT, and RIGHT joins.",
                            CourseId = 3,
                            Order = 2,
                            Title = "Joins"
                        },
                        new
                        {
                            Id = 9,
                            Content = "Improving query performance with indexes.",
                            CourseId = 3,
                            Order = 3,
                            Title = "Indexes & Performance"
                        },
                        new
                        {
                            Id = 10,
                            Content = "Selecting and updating DOM elements.",
                            CourseId = 4,
                            Order = 1,
                            Title = "DOM Basics"
                        },
                        new
                        {
                            Id = 11,
                            Content = "Making async requests with fetch.",
                            CourseId = 4,
                            Order = 2,
                            Title = "Fetch API"
                        },
                        new
                        {
                            Id = 12,
                            Content = "Handling user interaction with events.",
                            CourseId = 4,
                            Order = 3,
                            Title = "Events"
                        });
                });

            modelBuilder.Entity("MiniLearningPlatform.Api.Models.LessonCompletion", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CompletedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<int>("LessonId")
                        .HasColumnType("int");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("LessonId");

                    b.HasIndex("UserId", "LessonId")
                        .IsUnique();

                    b.ToTable("LessonCompletions");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CompletedAtUtc = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            LessonId = 1,
                            UserId = 1
                        });
                });

            modelBuilder.Entity("MiniLearningPlatform.Api.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("Username")
                        .IsUnique();

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            PasswordHash = "$2a$11$WMrQopuiDWXEaNxCK82ryO44u.1OGLQv0zBtMh2zMmP9/O2Dg/a8W",
                            Username = "testuser"
                        });
                });

            modelBuilder.Entity("MiniLearningPlatform.Api.Models.Enrollment", b =>
                {
                    b.HasOne("MiniLearningPlatform.Api.Models.Course", "Course")
                        .WithMany("Enrollments")
                        .HasForeignKey("CourseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MiniLearningPlatform.Api.Models.User", "User")
                        .WithMany("Enrollments")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Course");

                    b.Navigation("User");
                });

            modelBuilder.Entity("MiniLearningPlatform.Api.Models.Lesson", b =>
                {
                    b.HasOne("MiniLearningPlatform.Api.Models.Course", "Course")
                        .WithMany("Lessons")
                        .HasForeignKey("CourseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Course");
                });

            modelBuilder.Entity("MiniLearningPlatform.Api.Models.LessonCompletion", b =>
                {
                    b.HasOne("MiniLearningPlatform.Api.Models.Lesson", "Lesson")
                        .WithMany("Completions")
                        .HasForeignKey("LessonId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MiniLearningPlatform.Api.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Lesson");

                    b.Navigation("User");
                });

            modelBuilder.Entity("MiniLearningPlatform.Api.Models.Course", b =>
                {
                    b.Navigation("Enrollments");

                    b.Navigation("Lessons");
                });

            modelBuilder.Entity("MiniLearningPlatform.Api.Models.Lesson", b =>
                {
                    b.Navigation("Completions");
                });

            modelBuilder.Entity("MiniLearningPlatform.Api.Models.User", b =>
                {
                    b.Navigation("Enrollments");
                });
#pragma warning restore 612, 618
        }
    }
}
